# tasks file for cacti-rrd-backup
---
- name: install dependencies
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  with_items: "{{ cacti_rrd_backup_dependencies }}"
  tags:
    - configuration
    - cacti-rrd-backup
    - cacti-rrd-backup-install
    - cacti-rrd-backup-install-dependencies

- name: generate (backup) script
  template:
    src: usr/local/bin/cacti-rrd-backup.j2
    dest: "{{ cacti_rrd_backup_install_path }}/cacti-rrd-backup"
    owner: root
    group: root
    mode: 0750
    validate: '/usr/bin/env bash -n %s'
  tags:
    - configuration
    - cacti-rrd-backup
    - cacti-rrd-backup-configuration

- name: generate (restore) script
  template:
    src: usr/local/bin/cacti-rrd-restore.j2
    dest: "{{ cacti_rrd_backup_install_path }}/cacti-rrd-restore"
    owner: root
    group: root
    mode: 0750
    validate: '/usr/bin/env bash -n %s'
  tags:
    - configuration
    - cacti-rrd-backup
    - cacti-rrd-backup-configuration
